; Listing generated by Microsoft (R) Optimizing Compiler Version 19.32.31332.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__E032D042_concurrencysal@h DB 01H
__97E4103C_sal@h DB 01H
__B5428C7E_vadefs@h DB 01H
__038A8BC0_vcruntime@h DB 01H
__E757CEDD_xkeycheck@h DB 01H
__5FBC4476_yvals_core@h DB 01H
__7339CC27_limits@h DB 01H
__77D8FF8F_climits DB 01H
__6569C2CA_corecrt@h DB 01H
__995E897A_vcruntime_new@h DB 01H
__8AD92B59_vcruntime_new_debug@h DB 01H
__49916C16_crtdbg@h DB 01H
__AEA0015D_crtdefs@h DB 01H
__09B43BC2_use_ansi@h DB 01H
__45776BC2_yvals@h DB 01H
__741AE07E_corecrt_math@h DB 01H
__91D68F2D_math@h DB 01H
__6C20D4D3_corecrt_malloc@h DB 01H
__C9393812_stddef@h DB 01H
__D493B9BD_corecrt_search@h DB 01H
__1473E23E_corecrt_wstdlib@h DB 01H
__B49664B7_stdlib@h DB 01H
__F337DD7D_cstdlib DB 01H
__F2BA098B_xtr1common DB 01H
__1139447D_intrin0@inl@h DB 01H
__B78DB856_intrin0@h DB 01H
__F55E1E8B_cmath DB 01H
__A2143F22_corecrt_stdio_config@h DB 01H
__829E1958_corecrt_wstdio@h DB 01H
__6DFAE8B8_stdio@h DB 01H
__1AB86400_cstdio DB 01H
__CDDAF8CA_errno@h DB 01H
__836076BB_vcruntime_string@h DB 01H
__1FEB9909_corecrt_memcpy_s@h DB 01H
__A751F051_corecrt_memory@h DB 01H
__9200769A_corecrt_wstring@h DB 01H
__32E5F013_string@h DB 01H
__BFA5759D_cstring DB 01H
__C6E16F6F_corecrt_wconio@h DB 01H
__5DB64B66_corecrt_wctype@h DB 01H
__CB8D9B53_corecrt_wdirect@h DB 01H
__A9063C41_corecrt_share@h DB 01H
__6D390390_corecrt_wio@h DB 01H
__61BDDCD5_corecrt_wprocess@h DB 01H
__1157D6BA_corecrt_wtime@h DB 01H
__64F617E8_types@h DB 01H
__1DC1E279_stat@h DB 01H
__93DC0B45_wchar@h DB 01H
__8033B253_cwchar DB 01H
__56FC07D0_cstddef DB 01H
__FAF4A671_initializer_list DB 01H
__3325CFE4_xstddef DB 01H
__C3F33765_iosfwd DB 01H
__CD4FE218_stdint@h DB 01H
__4E693C00_cstdint DB 01H
__A9FE0816_type_traits DB 01H
__C43A58F6_utility DB 01H
__A1979AE5_xutility DB 01H
__B03B2DA5_iterator DB 01H
__5B81F060_share@h DB 01H
__4078F9B8___msvc_system_error_abi@hpp DB 01H
__879910FB_cerrno DB 01H
__20BB4341_malloc@h DB 01H
__3C5D8049_corecrt_terminate@h DB 01H
__119A4E8D_eh@h DB 01H
__82372E0B_vcruntime_exception@h DB 01H
__66FF6FCB_exception DB 01H
__158E8E48_float@h DB 01H
__69FCAF87_cfloat DB 01H
__50EB7CC8_isa_availability@h DB 01H
__0F1AE2E3_limits DB 01H
__3009A94F_new DB 01H
__6CF3E31D_xatomic@h DB 01H
__AEAF3B35_xmemory DB 01H
__DA7CBDA9_xstring DB 01H
__EFB15596_stdexcept DB 01H
__1C249A26_xcall_once@h DB 01H
__EDE27ECD_xerrc@h DB 01H
__A0B61CF9_time@h DB 01H
__33ED8283_ctime DB 01H
__175379A4_xtimec@h DB 01H
__68FA0C71_xthreads@h DB 01H
__642FBE21_atomic DB 01H
__A3798806_system_error DB 01H
__2BD565E5_vcruntime_typeinfo@h DB 01H
__D14869FC_typeinfo DB 01H
__B3B4EE6D_memory DB 01H
__9FF1B962_xfacet DB 01H
__55C17482___msvc_xlocinfo_types@hpp DB 01H
__B2D2BA86_ctype@h DB 01H
__157383A7_cctype DB 01H
__A3D09DBA_locale@h DB 01H
__609B01AC_clocale DB 01H
__CEC18A34_xlocinfo DB 01H
__0542C998_xlocale DB 01H
__F724FD27_xiosbase DB 01H
__ED11ED2A_streambuf DB 01H
__9BC5AF8F_xlocnum DB 01H
__C8C49359_ios DB 01H
__1652135C_ostream DB 01H
__75822666_istream DB 01H
__C3EEE0FA_iostream DB 01H
__239CF4BC_Main@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0O@KLMCIIGF@Hello?0?5World?$CB@		; `string'
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ:PROC
EXTRN	?Log@@YAXPEBD@Z:PROC				; Log
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+33
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+56
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0O@KLMCIIGF@Hello?0?5World?$CB@
CONST	SEGMENT
??_C@_0O@KLMCIIGF@Hello?0?5World?$CB@ DB 'Hello, World!', 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025030b01H
	DD	0b206230bH
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025031401H
	DD	0b20f2314H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025030f01H
	DD	0b20a230fH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File E:\Programming\C++\Cherno_compiler\Cherno_compiler\Main.cpp
; Line 6
$LN3:
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__239CF4BC_Main@cpp
	call	__CheckForDebuggerJustMyCode
; Line 7
	lea	rcx, OFFSET FLAT:??_C@_0O@KLMCIIGF@Hello?0?5World?$CB@
	call	?Log@@YAXPEBD@Z				; Log
; Line 8
	mov	rcx, QWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	QWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ
; Line 9
	xor	eax, eax
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 80
__formal$ = 88
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File E:\Programming\C++\Cherno_compiler\Cherno_compiler\Main.cpp
; Line 10
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__239CF4BC_Main@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 80
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File E:\Programming\C++\Cherno_compiler\Cherno_compiler\Main.cpp
; Line 10
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__239CF4BC_Main@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
